import os

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', "NO_ACCESS_KEY_SET_IN_ENV")
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', "NO_SECRET_KEY_SET_IN_ENV")
print(AWS_ACCESS_KEY_ID)
print(AWS_SECRET_ACCESS_KEY)
